advanced:
  network_key:
    - 45
    - 1
    - 224
    - 49
    - 26
    - 150
    - 205
    - 137
    - 192
    - 144
    - 158
    - 104
    - 110
    - 114
    - 9
    - 10
  pan_id: 57827
  channel: 25
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: eiceipaechu9phai1Mohng4cohPh0eit2faihighae3veipo6eaH1shaiw9Xaiyi
frontend:
  enabled: true
  port: 8099
serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20221201080813-if00
  adapter: ember
device_options: {}
devices:
  '0x001788010898ca29':
    friendly_name: Michaels Office Desk Lamp
  '0x00178801020a2bc7':
    friendly_name: Michaels Office Overhead Back Wall
  '0x0017880102f31996':
    friendly_name: Michaels Office Overhead Closet
  '0x0017880102204bba':
    friendly_name: Michaels Office Overhead Desk
  '0x001788010113975c':
    friendly_name: Michaels Office Uplight
  '0xb0ce1814032edfa5':
    friendly_name: Living Room Bulb 1
  '0xb0ce1814032d3199':
    friendly_name: Living Room Bulb 2
  '0xb0ce1814032ee8ef':
    friendly_name: Living Room Bulb 3
  '0xb0ce1814032eef43':
    friendly_name: Living Room Bulb 4
  '0xb0ce1814032c80e8':
    friendly_name: Living Room Bulb 5
  '0xb0ce1814032edf79':
    friendly_name: Hallway Bulb 1
  '0xb0ce1814032c7fc7':
    friendly_name: Hallway Bulb 2
  '0xb0ce1814032c81c1':
    friendly_name: Hallway Bulb 3
  '0xb0ce1814032c66f1':
    friendly_name: Hallway Bulb 4
  '0x001788010898ca69':
    friendly_name: Archers Bedroom Dresser
  '0x00178801011fd9c8':
    friendly_name: Archers Bedroom Bed Light
  '0x00178801028a49fa':
    friendly_name: Bedroom Dresser
  '0x0017880110400d5f':
    friendly_name: Bedroom MJK Bedside
  '0x00178801105b7523':
    friendly_name: Bedroom CCK Bedside
  '0x001788010bc17034':
    friendly_name: Garage Bulb Left
  '0x001788010bc15eab':
    friendly_name: Garage Bulb Right
  '0x001788010625db5c':
    friendly_name: Front Candys Office
  '0x00178801062772db':
    friendly_name: Front Michaels Office
  '0x001788010d49ce61':
    friendly_name: Porch Overhead Bulb 3
  '0x001788010d49ce46':
    friendly_name: Porch Overhead Bulb 4
  '0x001788010d49cec3':
    friendly_name: Porch Overhead Bulb 1
  '0x001788010d49ce7e':
    friendly_name: Porch Overhead Bulb 2
  '0x282c02bfffe6db05':
    friendly_name: Dining Room Repeater
  '0x282c02bfffe8b63e':
    friendly_name: Hallway Repeater
  '0x282c02bfffe8cb89':
    friendly_name: Upstairs TV Outlet
  '0x00124b0022d5f9a3':
    friendly_name: Bedroom Repeater
  '0x000d6f0003bf5a9f':
    friendly_name: Coffee Switch
  '0x90395efffe0feee2':
    friendly_name: Michaels Office 4-Button Controller
  '0x286d97000107a4a2':
    friendly_name: Michaels Office Door
  '0x282c02bfffe86622':
    friendly_name: Archers Bedroom Door
  '0xa4c13852a506917f':
    friendly_name: Small Hallway Motion
  '0xa4c1380bc5e10eea':
    friendly_name: Bedroom Door
  '0x282c02bfffed45f9':
    friendly_name: Bedroom Motion
  '0x00124b002a4f5a0b':
    friendly_name: Mudroom Motion
  '0x282c02bfffe869e4':
    friendly_name: Front Door
  '0x282c02bfffe871a6':
    friendly_name: Dog Food Container
  '0x00124b002a4ed235':
    friendly_name: Hallway Motion by Doorbell Sensor
  '0x00124b002932ce81':
    friendly_name: '0x00124b002932ce81'
  '0xa4c138989749fbcf':
    friendly_name: Candys Office Door
  '0xa4c138f5aa095bee':
    friendly_name: Archers Bedroom Window - Side
  '0xa4c1383fa239339d':
    friendly_name: Archers Bedroom Window - Back
  '0xa4c1387f3608d7f4':
    friendly_name: Downstairs Window 1
  '0xa4c13844f7590c7b':
    friendly_name: Downstairs Window 2
  '0xa4c138b8764ec65e':
    friendly_name: Downstairs Window 3
  '0xa4c138cc0d6c0519':
    friendly_name: Downstairs Window 4
  '0xa4c138cf270e9886':
    friendly_name: Downstairs Window 5
  '0xa4c1385f9dcec437':
    friendly_name: Downstairs Window 6
  '0x00124b0022ce7bed':
    friendly_name: TV Downstairs Outlet
  '0xa4c138b20146efb3':
    friendly_name: '0xa4c138b20146efb3'
  '0x00124b002fa13db6':
    friendly_name: '0x00124b002fa13db6'
  '0x282c02bfffe6dd44':
    friendly_name: Wall Panel Charger
homeassistant:
  enabled: true
version: 3
